name: commuter_guide
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points: ^3.1.0
  geolocator: ^14.0.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.6.0
  intl: ^0.20.2
  location: ^8.0.1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
